name: Flutter Build APK Release

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Remove dangling flutter submodule nếu có
      - name: Remove dangling flutter submodule
        run: |
          if [ -d "flutter" ]; then
            git rm -r --cached flutter || true
            rm -rf flutter
          fi

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build APK release
      - name: Build APK
        run: |
          flutter clean
          flutter build apk --release
